### ISSUE TITLE
Use proper template engine

### ISSUE THREAD

**Issue by theduke** [ashleygwilliams/cargo-generate#51]
As mentioned on Reddit, 
I think this crate is not very useful without more advanced customization based on variables. 
This would require a template engine though.

Example:

`Cargo.toml`
```
{% if use_serde %}
serde = "1.*"
serde_derive = "1.*"
{% endif %}
```

`lib.rs`
```
{% if db_type = "postgres" % } 
type Connection = diesel::pg::PgConnection;
{% elseif db_type = "mysql" % } 
...
{% endif %}
```

Two options for a template engine that come to mind:

* https://github.com/Keats/tera (used it myself, works well)
* https://github.com/sunng87/handlebars-rust

**Comment by ashleygwilliams** [comment]
hey! so the primary goal of this is so that you can easily bootstrap a project with a set of dependencies. think of templates almost like a way to receive a curated list of dependencies and an example of them working together. i think we are open to adding more things that can be replaced but for the moment i'm not convinced that conditional replacement is necessary. 

i'd love to see an example you'd like to create that would require this tho! so i would recommend experimenting with creating a template and then refiling an issue with a specific example! thanks :)

**Comment by epage** [comment]
@theduke To add to what @ashleygwilliams said, a proper template language is being used (as compared to regexes or a runtime version of `format!`), Liquid.  The difference is this project is taking a conservative approach to what tags and filters are exposed, starting with nothing and expanding from there.

Already in another [issue](https://github.com/ashleygwilliams/cargo-generate/issues/48), I've brought up the need for `heck` based filters.

I've gone ahead and created a dedicated issue for conditional tags, https://github.com/ashleygwilliams/cargo-generate/issues/68, because I know those would be relevant for me.
